kind: Cluster
apiVersion: kind.x-k8s.io/v1alpha4
networking:
  apiServerAddress: "0.0.0.0"
  apiServerPort: 6443
nodes:
- role: control-plane
  kubeadmConfigPatches:
  - |
    kind: ClusterConfiguration
    apiServer:
      certSANs:
        - "0.0.0.0"
        - "localhost"
        - "130.147.217.178"
  extraPortMappings:
  - containerPort: 6443
    hostPort: 16443
containerdConfigPatches:
  - |-

    [plugins."io.containerd.grpc.v1.cri".registry]
      [plugins."io.containerd.grpc.v1.cri".registry.configs]
        [plugins."io.containerd.grpc.v1.cri".registry.configs."docker.io"]
          [plugins."io.containerd.grpc.v1.cri".registry.configs."docker.io".tls]
            insecure_skip_verify = true
        [plugins."io.containerd.grpc.v1.cri".registry.configs."gcr.io"]
          [plugins."io.containerd.grpc.v1.cri".registry.configs."gcr.io".tls]
            insecure_skip_verify = true
        [plugins."io.containerd.grpc.v1.cri".registry.configs."pww.artifactory.cdi.philips.com"]
          [plugins."io.containerd.grpc.v1.cri".registry.configs."pww.artifactory.cdi.philips.com".tls]
            insecure_skip_verify = true
        [plugins."io.containerd.grpc.v1.cri".registry.configs."quay.io"]
          [plugins."io.containerd.grpc.v1.cri".registry.configs."quay.io".tls]
            insecure_skip_verify = true
        [plugins."io.containerd.grpc.v1.cri".registry.configs."ghcr.io"]
          [plugins."io.containerd.grpc.v1.cri".registry.configs."ghcr.io".tls]
            insecure_skip_verify = true

      [plugins."io.containerd.grpc.v1.cri".registry.mirrors]
        [plugins."io.containerd.grpc.v1.cri".registry.mirrors."docker.io"]
          endpoint = ["http://nexus.devops.philips-healthsuitechina.com.cn:5000"]
        [plugins."io.containerd.grpc.v1.cri".registry.mirrors."gcr.io"]
          endpoint = ["http://nexus.devops.philips-healthsuitechina.com.cn:5002"]
        [plugins."io.containerd.grpc.v1.cri".registry.mirrors."pww.artifactory.cdi.philips.com"]
          endpoint = ["http://nexus.devops.philips-healthsuitechina.com.cn:5005"]
        [plugins."io.containerd.grpc.v1.cri".registry.mirrors."quay.io"]
          endpoint = ["http://nexus.devops.philips-healthsuitechina.com.cn:5001"]
        [plugins."io.containerd.grpc.v1.cri".registry.mirrors."ghcr.io"]
          endpoint = ["http://nexus.devops.philips-healthsuitechina.com.cn:5006"]